version: "3.9"

services:
  db:
    image: postgres:15
    container_name: educoin_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: educoin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: educoin_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: educoin_app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run start:prod
      "
    environment:
      DATABASE_URL: postgres://postgres:12345@db:5432/educoin
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
